# Назва вашого автоматичного процесу
name: Playwright Tests

# Умови запуску:
# - Коли відбувається push у гілку 'main'
# - Коли створюється Pull Request до гілки 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

# Завдання, які будуть виконуватись
jobs:
  test:
    # Вказуємо операційну систему для запуску
    runs-on: ubuntu-latest

    # Кроки, які виконуватимуться послідовно
    steps:
      # 1. Клонуємо репозиторій, щоб мати доступ до коду
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Встановлюємо Python вказаної версії
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Вкажіть вашу версію Python

      # 3. Встановлюємо залежності проєкту
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest pytest-playwright
          pip install -r requirements.txt
          pip install allure-pytest

      # 4. Встановлюємо браузери для Playwright
      - name: Install Playwright browsers
        run: playwright install chromium --with-deps # --with-deps встановить залежності для Linux

      - name: Install Allure CLI manually
        run: |
            curl -Lo allure.tgz https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
            tar -zxvf allure.tgz
            sudo mv allure-2.27.0 /opt/allure
            sudo ln -s /opt/allure/bin/allure /usr/bin/allure
            allure --version

      # 5. Запускаємо тести з генерацією результатів Allure
      - name: Run Playwright tests
        run: pytest --alluredir=allure-results

      - name: Check Allure results exist
        run: ls -la allure-results

      # 6. Генеруємо HTML-звіт Allure з отриманих результатів
      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      # 7. Завантажуємо звіт як артефакт для GitHub Pages
      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
            path: allure-report

      - name: Fail job if tests failed
        if: steps.tests.outputs.exit_code != '0'
        run: |
            echo "Some tests failed"
            exit 1

  # Завдання для публікації звіту
  deploy:
    name: Deploy Allure report to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4